backend:
  name: github
  repo: pinkyo3o/pinkyo3o.github.io
  branch: main
  auth_type: oauth
  app_id: Ov23liyoKU4JPzBtqB8q
  base_url: https://decap-oauth.850339551.workers.dev
  auth_endpoint: /auth

media_folder: "public/images"
public_folder: "/images"

publish_mode: simple
locale: 'zh_Hans'

collections:
  - name: "zh"
    label: "📝 中文博客"
    folder: "src/content/blog/zh"
    create: true
    delete: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "摘要", name: "description", widget: "string" }
      - { label: "发布日期", name: "pubDate", widget: "datetime" }
      - { label: "更新日期", name: "updatedDate", widget: "datetime", required: false }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "语言", name: "lang", widget: "select", options: ["zh"], default: "zh" }
      - { label: "草稿", name: "draft", widget: "boolean", default: false }
      - { label: "正文", name: "body", widget: "markdown" }

  - name: "en"
    label: "📝 English Blog"
    folder: "src/content/blog/en"
    create: true
    delete: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Updated Date", name: "updatedDate", widget: "datetime", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Language", name: "lang", widget: "select", options: ["en"], default: "en" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
